### ISSUE TITLE
Exception: /home/pikdum/.local/share/Steam not found

### ISSUE THREAD

**Issue by pikdum** [wyyadd/LaLa#1]
When trying to launch anything, I'm getting:

> Exception: /home/pikdum/.local/share/Steam not found

Looks like it's expecting Steam to be here, but when installing Steam from my distro's package repositories it's elsewhere:

```console
$ ll ~/.steam/
total 20K
lrwxrwxrwx  1 pikdum pikdum   25 Nov  4 12:54 bin -> /home/pikdum/.steam/bin32
lrwxrwxrwx  1 pikdum pikdum   51 Nov  4 12:54 bin32 -> /home/pikdum/.steam/debian-installation/ubuntu12_32
lrwxrwxrwx  1 pikdum pikdum   51 Nov  4 12:54 bin64 -> /home/pikdum/.steam/debian-installation/ubuntu12_64
drwxrwxr-x 29 pikdum pikdum 4.0K Nov  4 15:40 debian-installation
-rwxrwxr-x  1 pikdum pikdum 5.2K Nov  4 12:54 registry.vdf
lrwxrwxrwx  1 pikdum pikdum   39 Nov  4 12:54 root -> /home/pikdum/.steam/debian-installation
lrwxrwxrwx  1 pikdum pikdum   47 Nov  4 12:54 sdk32 -> /home/pikdum/.steam/debian-installation/linux32
lrwxrwxrwx  1 pikdum pikdum   47 Nov  4 12:54 sdk64 -> /home/pikdum/.steam/debian-installation/linux64
lrwxrwxrwx  1 pikdum pikdum   39 Nov  4 12:54 steam -> /home/pikdum/.steam/debian-installation
-rw-rw-r--  1 pikdum pikdum    5 Nov  4 12:54 steam.pid
prw-------  1 pikdum pikdum    0 Sep 25 18:07 steam.pipe
-r--------  1 pikdum pikdum   16 Nov  4 12:54 steam.token
```

I'm on PopOS, but I'm guessing it's similar on Debian and Ubuntu.

This is the path I usually use to get to my games: `~/.steam/steam/steamapps/common`

It's also not detecting any installed games, so Library is empty.

Thanks!

**Comment by wyyadd** [comment]
Thanks for the issue.
Default steam path in LaLa is $home/.local/share/Steam
I will fix this in next release.

**Comment by ahjolinna** [comment]
support for flatpak steam install locations would be good to have

`/home/ahjolinna/.var/app/com.valvesoftware.Steam/data/Steam/`

**Comment by wyyadd** [comment]
@ahjolinna 
Thank you for reminding. I will allow users to choose the Steam installation path, not just the default one.

**Comment by wyyadd** [comment]
In the commit https://github.com/wyyadd/LaLa/commit/07d5e0d2d16835c74b9cd0ee0cc935234384282d, I've added the feature to set the Steam path in the settings page. This issue should be resolved. Release 1.0.3 is avaliable.

**Comment by ahjolinna** [comment]
seems to be working, at least on openSUSE [MicroOS/Kalpa](https://get.opensuse.org/microos/) could choose the flatpak steam and then it found just fine....now just have to test how it works

**Comment by pikdum** [comment]
Seems to be working now, thanks!

**Comment by MW2K** [comment]
Sorry to necro this, but I cannot set the path in Kubuntu 23.10. Like the OP, Steam installs games to ~/.steam/steam/steamapps/common If I set that as the path, it fails. Same if I just set it to ~/.steam So, what is the steam path? The funny thing is that Steam itself has set a broken symlink:
`.steampath -> /home/peter/.steam/sdk32/steam`
I've tried this as the path, but that doesn't work either - nothing exists at `/home/peter/.steam/sdk32/steam`
So I'm stuck - Google gives me a half-dozen answers as to what is the steam path, so I'm hoping someone can help!

**Comment by wyyadd** [comment]
@MW2K Hi, Have you tried setting steampath to ``` ~/.steam/steam``` or ```~/.local/share/Steam```?

**Comment by oodzchen** [comment]
I'm use EndeavourOS, the steampath is right, it shows load games successfully, but there nothing in the launcher, but I've already installed several games on my system.

**Comment by wyyadd** [comment]
hi @oodzchen , you can search and add games manually.
LaLa reads ```$steamPath/steamapps/libraryfolders.vdf``` file to load games. 
You can check this file and make sure there are app Ids.

**Comment by oodzchen** [comment]
@wyyadd Yes the file is there, and I can see apps Ids. I've tried load games in the settings, it shows games loaded successfully directly, no other input options or something, and there still no games in it.

**Comment by wyyadd** [comment]
@oodzchen Hi, my fault. 
Our server was down before so you can't load games. I just restart server. 
Please try again. I believe this time you can load games successfully.

**Comment by oodzchen** [comment]
@wyyadd Now I see the games, but nothing happened after I clicked the launch button, even after change the trainer version. And this error still in the log:
> Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

**Comment by oodzchen** [comment]
@wyyadd I just change the Proton Experimental to Proton9.0-3, now it works.
