### ISSUE TITLE
The trainer for the game does not open in Steam Deck's Gaming Mode

### ISSUE THREAD

**Issue by xmkgfm** [wyyadd/LaLa#10]
LaLa works great in Steam Deck's Desktop Mode.

However, when the SD is in the gaming mode, when LaLa is opened simultaneously, the trainer for the game that's already running will not open. (LaLa itself runs)

In gaming mode, 

Run game A, run LaLa, can't open the trainer for game A (no dialogue/message box of any sort), can open the trainer for game B.

Run game B, run LaLa, can't open the trainer for game B, but this time it can open the trainer for game A.

Of course, since the trainers that can be opened are not meant for the game already running, one cannot use LaLa in the gaming mode.

Because of this, I believe it's not the invalid trainers' fault.

**Comment by wyyadd** [comment]
Thank you for the issue. 
Currently, LaLa's experience in gaming mode is not perfect. I'm actively working on improving this.
related issue: https://github.com/wyyadd/LaLa/issues/7

**Comment by wyyadd** [comment]
Hi @xmkgfm. In the [v1.0.5 release](https://github.com/wyyadd/LaLa/releases/tag/v1.0.5), I've made some optimizations for SteamDeck's gaming mode.

However, I couldn't reproduce the issue you mentioned. Have you tried switching windows in gaming mode as some trainers won't pop up.
Please try the latest version, and I look forward to hearing your feedback.

**Comment by xmkgfm** [comment]
Hi,

I have tried the latest version of LaLa, but the same issue persists. 

In gaming mode,

if I run the game first and run LaLa, the trainer for the game will not open. Trainers for other games will open.
If I run LaLa and the trainer first and run the game, the game will not open.
If I run Lala first, the game second, and try to open the trainer for the game, the trainer for the game will not open. Trainers for other games will open.

When LaLa opens trainers for the other games, I do see options to switch to different windows. So not seeing them when I try to run the trainer for the game highly suggests that the trainer was never opened successfully.

![aaa](https://github.com/wyyadd/LaLa/assets/150044345/382f0e39-c567-48a9-8671-7a53cfa6c686)

**Comment by Mte90** [comment]
There is something we can do to help you with Steam Deck and gaming mode?
Maybe a debug build? I can use the terminal on the SD and generate a log if you want.

**Comment by ahjolinna** [comment]
@wyyadd I dont know if this help but I found this article : https://overkill.wtf/how-to-use-cheats-on-steam-deck/

**Comment by wyyadd** [comment]
Hello,
With the release of [LaLa 1.1.0](https://github.com/wyyadd/LaLa/releases/tag/v1.1.0), this issue should be resolved. 
If you still encounter any problems, feel free to reopen this issue.

**Comment by Mte90** [comment]
The readme isn't clear after this last release.
Lala start in gaming mode (I installed as flatpak), but after pressing launch of the trainer nothing happens.

It is still required the desktop mode?

**Comment by wyyadd** [comment]
Hi @Mte90 
Please check [Important notice for Linux and Steam Deck user](https://github.com/wyyadd/LaLa?tab=readme-ov-file#%EF%B8%8F-important-notice-for-linux-and-steam-deck-user)
> For Steam Deck users who use LaLa in gaming mode:
    - Please add LaLa as a non-steam game.
    - Flatpak LaLa is **not supported** for gaming mode.
    - Use Mouse Only button Layout for better experience.
 
Flatpak LaLa is **not supported** for gaming mode. Please use Appimage or binary version.

**Comment by Mte90** [comment]
I will switch to the appimage version.
