### ISSUE TITLE
Launching custom trainers

### ISSUE THREAD

**Issue by revanmj** [wyyadd/LaLa#17]
Since your app can launch trainers easily without all the Steam Tinker Launch shenanigans, is there any chance you could add option to manually add trainers? (choose game for which they are and point to trainer exe file)

**Comment by wyyadd** [comment]
Thank you for bringing up this issue. 
In the future, I plan to implement a feature where users can manually add trainers or other tools. 
Stay tuned for updates!

**Comment by wyyadd** [comment]
Hi @revanmj, 
You can add custom trainers now in [Release v1.0.6](https://github.com/wyyadd/LaLa/releases/tag/v1.0.6)
I am looking forward to hearing your feedback.

**Comment by revanmj** [comment]
Seems to be working fine, but the error shown when launching custom trainer without any game running should be changed to clearly indicate that in case of custom trainers, game must be started first (or show such message when adding custom trainer). 

I initially tried to set the name to be exact match of the on Steam or find out how to set the game id for the custom trainer because error said that game path could not be found.

But this mechanic (not having to tie custom trainer to a specific game) is good, because it can be used with generic trainers like CH Aurora too without creating separate entries for each game.

**Comment by wyyadd** [comment]
> Seems to be working fine, but the error shown when launching custom trainer without any game running should be changed to clearly indicate that in case of custom trainers, game must be started first (or show such message when adding custom trainer).

Thank you for bringing this to my attention. I will update the corresponding error message to clearly indicate that.

> I initially tried to set the name to be exact match of the on Steam or find out how to set the game id for the custom trainer because error said that game path could not be found.
But this mechanic (not having to tie custom trainer to a specific game) is good, because it can be used with generic trainers like CH Aurora too without creating separate entries for each game.

For custom trainers or non-steam games, LaLa automatically detects them when games are running, without the need to specify the corresponding appid.

**Comment by nexusjack** [comment]
> I initially tried to set the name to be exact match of the on Steam or find out how to set the game id for the custom trainer because error said that game path could not be found.
> 


Ah, I think this is the confusion I am having.   I add a new trainer and the error message shows a path with a 'random' or at least incorrect appid.

So each trainer I manually add to LaLa needs to have it's game launched first?

**Comment by wyyadd** [comment]
Update:
I have updated error messages for custom trainers in [v1.0.7](https://github.com/wyyadd/LaLa/releases/tag/v1.0.7)
