### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Laz55** [wyyadd/LaLa#18]
Hi

Underneath  you have the console commands  too install the launcher for steamdeck ;however,  it doesn't  work at all. When you  copy  paste the scripts  theu do not work at. Installation  script  is broken  and does not work  at in the Konsole.

**Comment by wyyadd** [comment]
Thank you for you issue.
What script are you using, and what errors are you encountering when trying to install the launcher?

**Comment by ahjolinna** [comment]
the flatpak installation worked just fine for me on SteamDeck and my Deskop PC. 

check that when you run the console command that its run in the same directory as where the flatpak file is downloaded to.

I assume its in download dir. so run: 

`cd /home/deck/Downloads/`
then
`flatpak install --user LaLa_linux_amd64.flatpak`

**Comment by wyyadd** [comment]
Haven't received a response for an extended period, so close the issue. 
If you still encounter issues during installation, please reopen this issue.

**Comment by Laz55** [comment]
> the flatpak installation worked just fine for me on SteamDeck and my Deskop PC.
> 
> check that when you run the console command that its run in the same directory as where the flatpak file is downloaded to.
> 
> I assume its in download dir. so run:
> 
> `cd /home/deck/Downloads/` then `flatpak install --user LaLa_linux_amd64.flatpak`

 I litttly  copped that and it would  install  it at all.

**Comment by wyyadd** [comment]
@Laz55  Seems you don't have flatpak on your os. 
Please follow instructions in https://flatpak.org/ to install flatpak. 
Or  run appImage file directly.

**Comment by Laz55** [comment]
Okay thank  you.  I will try this out  when I get home.
