### ISSUE TITLE
Error launching the AppImage on Arch

### ISSUE THREAD

**Issue by Sojiro84** [wyyadd/LaLa#3]
When running the AppImage I get the following error:

```
~/Applications $ ./LaLa_linux_amd64_cb1cbb9cd01a532feb566246ba2e1234.AppImage
Gtk-Message: 09:19:42.209: Failed to load module "colorreload-gtk-module"
Gtk-Message: 09:19:42.210: Failed to load module "window-decorations-gtk-module"

(LaLa:329471): Gtk-WARNING **: 09:19:42.230: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/window-minimize-symbolic.symbolic.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

I am on Arch, KDE Plasma.

if you need more information, let me know!

**Comment by wyyadd** [comment]
Thank you for the issue.
Look likes a gtk error.
LaLa depends on the following packages:
libgtk-3-0, libblkid1, liblzma5
Have your os installed these packages?

**Comment by Sojiro84** [comment]
I can't find them with those exact names, but searching for:

**libgtk** gives: "gtk3 1:3.24.38-1 (7.7 MiB 48.9 MiB) (**Installed**), GObject-based multi-platform GUI toolkit"

**libblkid** gives:

- "lib32-util-linux 2.39.2-1 (410.3 KiB 1.1 MiB) (**Installed**), Miscellaneous system utilities for Linux (32-bit)"

- "util-linux-libs 2.39.2-1 (445.1 KiB 1.2 MiB) (**Installed**), util-linux runtime libraries"

**liblzma** gives:

- lib32-xz 5.4.4-1 (106.3 KiB 225.7 KiB) (**Installed**), Library and command line tools for XZ and LZMA compressed files (32-bit)

- xz 5.4.4-1 (613.1 KiB 2.3 MiB) (**Installed**), Library and command line tools for XZ and LZMA compressed files

**Comment by wyyadd** [comment]
@Sojiro84 I've just made LaLa compatible with the Flatpak format, which should work better on Arch systems. 
You can try installing the Flatpak version of LaLa, and I look forward to receiving your feedback.

**Comment by Sojiro84** [comment]
Yes, that worked and it launches now. Have yet to try it with a game though. Thanks!

**Comment by wyyadd** [comment]
You are welcome. Enjoy your gaming.
