### ISSUE TITLE
Some trainers can't launch on Linux or SteamDeck

### ISSUE THREAD

**Issue by ODSTIgnasi** [wyyadd/LaLa#4]
So I added my steam path(I'm on Ubuntu), pressing launch doesn't prompt 'Exception: Steam path not found.' anymore, but it also doesn't do anything else either, how should the app work? The game is RE4 by the way.

**Comment by wyyadd** [comment]
I believe this might be related to the trainer's version. I tried the v20230921 version, and it also didn't open the trainer, but after switching to some older versions, it worked successfully.

**Comment by wyyadd** [comment]
I will investigate this issue further.

**Comment by wyyadd** [comment]
Update: 
related issue: https://github.com/madewokherd/wine-mono/issues/167|

**Comment by wyyadd** [comment]
Update: 
related post: [fling_trainer_fix](https://www.reddit.com/r/SteamDeck/comments/15owi1l/fling_trainer_fix/) and [Recent Fling Trainers do not work?](https://www.reddit.com/r/SteamDeck/comments/1683bfg/recent_fling_trainers_do_not_work/)
> after much troubleshooting, seems to be a problem with .NET runtime. mscoree.dll dependency.

After using winetricks to install dotnet40,  I can run RE4 rainers successfully.
I will write a tutorial on how to install dotnet40 using winetricks.

**Comment by wyyadd** [comment]
Update: 
I wrote a tutorial on how to [reinstall dotnet40](https://github.com/wyyadd/LaLa/blob/master/docs/reinstall_dotnet40.md)
Also I updated [FAQ README](https://github.com/wyyadd/LaLa/blob/master/README.md#on-linux-or-steam-deck-why-some-trainers-wont-start).
This issue can be closed.
