### ISSUE TITLE
App not detecting Steam path on SD Card

### ISSUE THREAD

**Issue by razoalghul** [wyyadd/LaLa#41]
Hello! On Steam Deck, my games are on the SD card.

I installed the launcher following instructions and it launched fine in desktop mode. When adding games, I search for a game and click "launch". This prompts me to set the Steam path. I navigate to the steamapps folder on my SD Card but the game won't launch and says that "LAUNCH FAILED - Exception: Steam path not found". I don't know what to do.

Thank you!

**Comment by wyyadd** [comment]
Hi @razoalghul 
> This prompts me to set the Steam path.  I navigate to the steamapps folder on my SD Card but the game won't launch and says that "LAUNCH FAILED - Exception: Steam path not found".

LaLa is looking for the path that include the "steamapps" folder. 
By default, this path should be ~/.steam/steam or ~/.local/share/Steam

One more thing,  FlakPak LaLa can **only** access home folders and **cannot** access folders on SD Card unless you grant the permission manually using Flatseal.
So, the workaround is either switching to AppImage LaLa or moving your game from SD card to steamdeck.

**Comment by wyyadd** [comment]
Hello,
With the release of [LaLa 1.1.0](https://github.com/wyyadd/LaLa/releases/tag/v1.1.0), this issue should be resolved. 
If you still encounter any problems, feel free to reopen this issue.
