### ISSUE TITLE
Arch Linux installation errors

### ISSUE THREAD

**Issue by anark10n** [wyyadd/LaLa#47]
Tried installing it on arch linux, and i get the following errors:
```
dpkg: dependency problems prevent configuration of lala-trainers-launcher:
 lala-trainers-launcher depends on libgtk-3-0; however:
  Package libgtk-3-0 is not installed.
 lala-trainers-launcher depends on libblkid1; however:
  Package libblkid1 is not installed.
 lala-trainers-launcher depends on liblzma5; however:
  Package liblzma5 is not installed.
```
The libraries are already installed, but for whatever reason, they're reported as not installed.

**Comment by wyyadd** [comment]
hi @anark10n 
.deb file is for debian based linux.
For arch linux, try AppImage or flatpak.

**Comment by wyyadd** [comment]
Hello,
With the release of [LaLa 1.1.0](https://github.com/wyyadd/LaLa/releases/tag/v1.1.0), this issue should be resolved. 
If you still encounter any problems, feel free to reopen this issue.
