### ISSUE TITLE
Proton path not found

### ISSUE THREAD

**Issue by Broshan84** [wyyadd/LaLa#48]
It tells me that proton path is not found 
Current Path: null
and there is no option to set the proton path except for steam. 
I added steam and still the same issue.

**Comment by Broshan84** [comment]
Also, why does the add steam option use a weird file explorer? it only shows my main drive mounted but I have games on 4 drives. it does know when the game is launched, but does not know where proton is

**Comment by wyyadd** [comment]
Hi @Broshan84 
> proton path is not found

This is because LaLa can only access your main drive.
You can either grant LaLa permission or move your game to main drive.
I will try fixing this issue in next version.

**Comment by wyyadd** [comment]
Hello,
With the release of [LaLa 1.1.0](https://github.com/wyyadd/LaLa/releases/tag/v1.1.0), this issue should be resolved. 
If you still encounter any problems, feel free to reopen this issue.
