### ISSUE TITLE
Game Not Found

### ISSUE THREAD

**Issue by WonderingViper** [wyyadd/LaLa#49]
Hey there, 

I first want to say your trainer is amazing and stopped me from switching back to windows.....

Now:::::

I have this problem- where certain games will not run for me on my system -unless I add 'clearcpuid=514' 
to my Grub options. Doing so allows the problem games to run but at the expense of trainers no longer detecting that any of my games are running. 

Could there be a possible fix to this?

(Note: I have tried searching for alternative ways to get the games to run without the 'fix' but to no avail.)

**Comment by wyyadd** [comment]
> Some small explanation what umip is: UMIP is a feature that disables certain CPU instructions from being run by user-space (non-root) applications. When the app tries to run them, it instantly crashes. However, as everything in wine runs in user-space, UMIP can cause problems for some windows apps that require the cpu instructions. Disabling it bypasses these problems. I don't think it should affect anything else : the only thing is that it might fix other cracks that had the same issue on your setup.  ------[source](https://www.reddit.com/r/CrackSupport/comments/119x8k0/comment/j9tfend/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) and https://github.com/ValveSoftware/Proton/issues/2927

From what I learned, disabling UMIP(i.e. ```clearcpuid=514```) can enable some special CPU instructions being run by non-root applications. 
I don't know why this feature could affect LaLa.

> Doing so allows the problem games to run but at the expense of trainers no longer detecting that any of my games are running.
Once the feature is enabled, are you unable to open all the trainers? If so, what specific error messages do you encounter?

**Comment by WonderingViper** [comment]
Nevermind🤦‍♂️. You can close this! Just tried again and oddly it works now. The issue was initially.

Boot the game, boot the trainer, trainer opens, enable cheats.

Then switching to "clearcpuid=514"

Boot the game, boot the trainer, trainer opens, "game process not found" or game is not running when it actually was running.

Removed 'clearcpuid=514' and the trainers would detect the game again.

Idk what the issue was since it is now working with 'clearcpuid=514' (same games/ same trainers but now detects with 'fix')

My sincerest apologies for wasting your time🙏

**Comment by wyyadd** [comment]
No worries, I'm glad to hear you resolved the issue! Enjoy your gaming! 
If you have any other questions in the future, feel free to reach out. 😊
