### ISSUE TITLE
When running trainer get "Access Denied"

### ISSUE THREAD

**Issue by vavalos** [wyyadd/LaLa#5]
When I try to run the trainer I get an "Access Denied" and saying that the Trainer get administrative access. I took a screen shot to show what error I get.

Is there a way to fix this?

![Screenshot_20231105_120738](https://github.com/wyyadd/LaLa/assets/4343124/06eda4c7-6970-42ba-95a1-cb0867ce2db5)

**Comment by wyyadd** [comment]
https://flingtrainer.com/trainer/dead-cells-trainer/comment-page-7/#comments
Looks like a known issue for steamdeck user.
Have you tried another version of trainer?

**Comment by vavalos** [comment]
I have, but its not your program. I ended up trying it on Death Stranding and it works fine. So looks like the trainer for this particular game.

**Comment by wyyadd** [comment]
Glad to hear that.
Enjoy your gaming！
