### ISSUE TITLE
Proton Not Found

### ISSUE THREAD

**Issue by Clevva-Hein** [wyyadd/LaLa#53]
I am trying to use LaLa on Nobara 40, I tried launcing the AppImage directly and setting my steam path, it detects the game but when I launch it it statests that proton is not found (Proton is installed even a custom one as well)

Further more I tried adding it as a non steam game and adding the launch options but it gave me the same error

**Comment by wyyadd** [comment]
Hi, does your game have a linux version? If so, you have to [force the game to use Proton](https://github.com/wyyadd/LaLa/blob/master/docs/enable_proton.md#how-to-force-the-game-to-use-proton).

**Comment by Clevva-Hein** [comment]
Yes I am forcing it, I tried at a force level (per game) as well as globally, and I also tried different versions of Proton

**Comment by wyyadd** [comment]
Where is the location of the proton?
Do you use a second drive? If so, you should mount your drive, then LaLa can access proton

**Comment by BeerDeveloper** [comment]
Having the same issue; i did some tests to find the cause and it appears that both game and proton version need to sit inside the steam installation path, which on debian is /home/user/steam/debian-installation/steamapps: if they both sit here, the trainer launches correctly

Combinations that do not work include:

- Game is located on another drive, Proton is located in steam installation folder
- Proton is located on another drive, game is located in steam installation folder
- Both game and Proton are on a drive that isn't the steam installation folder

I can also see that Lala Trainers Launcher tells me Proton not found, default path is *game path* when Proton is located in the steam installation folder: the best bet to solve the issue might be default the Proton location to the steam installation path, and users can have the care to install all their Proton versions there, or give the chance to the user to define a Proton installation folder _per game_, as a global one would also not work as many games use many different Proton versions.

**Comment by wyyadd** [comment]
With the release of [LaLa 1.1.1](https://github.com/wyyadd/LaLa/releases/tag/v1.1.1), this issue should be resolved.
If you still encounter any problems, feel free to reopen this issue.
