### ISSUE TITLE
[question] SteamDeck/SteamOS usage

### ISSUE THREAD

**Issue by ahjolinna** [wyyadd/LaLa#7]
How is the SteamDeck usage meant to be done?

are you meant to launch the app from the "Desktop Mode"? 
because currently at least for me in "Gaming Mode" I can't get the app to launch the trainer (the window won't pop-up)

**Comment by wyyadd** [comment]
Best practice is to use LaLa in "Desktop Mode".
You can add LaLa as a non-steam game. But I guess you can't run game and LaLa simultaneously.
(I don't have a steamdeck. Tested on ubuntu 22.04  Steam Big Picture Mode)

**Comment by ahjolinna** [comment]
I did tried the "non-steam game" way, thats the how I usually do it...as SteamOS has a button (in KDE) that "Add to Steam", so its easy.

Anyway, have you tried testing [holoiso](https://github.com/HoloISO/holoiso)? it's community ISO of the latest version of SteamOS with some changes to work on more devices.

**Comment by wyyadd** [comment]
Thank you for providing this information. I'll look into HoloISO. 
Many Steam Deck users surely prefer using Gaming mode.

**Comment by wyyadd** [comment]
I have successfully installed holoiso and conducted some testing on the Steam Deck. Thank you for your guidance.  :D 

Now, you can run LaLa in Steam Deck's gaming mode and launch Trainers.
However, there are still some issues with the flatpak version of LaLa. For more details, please check https://github.com/wyyadd/LaLa/issues/15.

**Comment by ahjolinna** [comment]
when I tested the app little it bit on the SteamDeck after 1.0.5 arrived, I notice that few things would be nice to have.

1) scrolling support when/if you have many games in your library. Even more than 10 games as  the 2nd row is cut in half.
Also you could make the game cover size same for "Library" as it's in "Games"

2) not sure if possible but would be nice when you press the search the touch keyboard would activate, now you have to manually press "steam-key + X" for it to activate

3) as SteamDeck has touchpads for mouse usage, it would be nice if you could use that instead of touchscreen

4) .....there was something else, but I forgot :D 

I guess some of these might be hard(er) to implement without having steamdeck on-hand
https://partner.steamgames.com/doc/steamdeck
https://partner.steamgames.com/doc/store/application/platforms/linux
https://github.com/ValveSoftware/SteamOS/wiki/How-To-and-Guides

**Comment by wyyadd** [comment]
Thank you for your suggestions and I appreciate your thoughtful feedback :D
1. It seems to be a bug where the gaming mode forcibly stretches LaLa from the 1280x720 window size to the entire screen, resulting in oversized game icons. I will add a "--full-screen" parameter to address this issue and allow LaLa to start in full-screen mode. 
On PC, I can scroll using the mouse wheel; on the Steam Deck, can you scroll using touch, similar to mobile devices?
2.  After some attempts, I found that I can't wake up the keyboard. It seems that calling Steam's API is necessary.  I'm currently exploring options to integrate this functionality.
3. When testing on the Steam Deck, I modified the controller's mapping settings to use the mouse.  Can you achieve this on a real Steam Deck?

**Comment by ahjolinna** [comment]
1)  when it comes to touchscreen it works as mouse, there is no multitouch support or scrolling option thingy

2) this is kinda a minor issue, as using "steam-key + X" for it to activate is kinda normal ...especially in-game and desktop

3) yes, when the app is open and press the "steam key" you can see "Controller settings", just choose a premade template layout (Gamepad with Mouse Trackpad). Not sure if possible to preconfigure to use that template by default


PS. as a side not, I was wondering why using Flutter? dont really care one way or another just wonder.
I'm more of a [Qt/Qml](https://www.qt.io/) (+[Rust](https://www.rust-lang.org/)) guy

**Comment by wyyadd** [comment]
A few months ago, I developed a mobile app using Flutter. 
When I started developing LaLa, I chose Flutter for its familiarity.  Personally, I'm not as experienced with the Qt framework🫣.
